# Site settings
title: SkylineBin的技术成长之路
description: "A blog about skylinebin ..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://skylinebin.com/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# url: "https://skylinebin.com/"
# User settings
username: SkylineBin
user_title: skylinebin - FrontEnd
email: skylinebin@outlook.com
twitter_username: liubin1995
github_username:  skylinebin
gplus_username:  115372092992473887120
disqus_username: skylinebin
weibo_username: skylinebin
linkedin_username: skylinebin
qq_id: "346821296"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
plugins: 
- jekyll-paginate
- jekyll-seo-tag
- jekyll-pwa-plugin

future: true

# start paginate
paginate: 10
paginate_path: "pagelist/page:num"

# LeanCloud
leancloud: 
  enable: true
  app_id: WJmvuueUfSFpusIzgyIGa0hW-gzGzoHsz
  app_key: jptI9djY9vTBuWGDR69VHakF


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# friend's links
friendlinks:
  title: friends' links
  url: /friends

# Support me link
supportme:
  title: support me
  url: /support

# Maybe helpful
helpfulposts:
  - name: 一个程序员的软件推荐指南
    url: https://skylinebin.com/WhenIGetANewComputer/
  - name: Windows下的快捷指令操作
    url: https://skylinebin.com/SomeshortcutCommands/


# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: posts
    url: /pagelist/
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about
    url: /about
  - title: tools
    url: /tools

# projects in header index
projects:
  - name: Machine-Learning-Notes
    url: https://github.com/skylinebin/Machine-Learning-Notes
  - name: AlgorithmPractice
    url: https://github.com/skylinebin/AlgorithmPractice
  - name: NoteBackend
    url: https://github.com/skylinebin/noteBackend
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# add pwa configuration  
pwa:
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"

livereload: true