# Site settings
title: skylinebin - Full Stack Learner
description: "A blog about skylinebin ..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "http://skylinebin.github.io/blog/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: SkylineBin
user_title: skylinebin - FrontEnd
email: whutliubin@gmail.com
twitter_username: liubin1995
github_username:  skylinebin
gplus_username:  115372092992473887120
disqus_username: skylinebin
weibo_username: skylinebin
linkedin_username: skylinebin
qq_id: "346821296"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
plugins: [jekyll-paginate]

# start paginate
paginate: 10
paginate_path: "pagelist/page:num"


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /pagelist/
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
  - title: little tools
    url: /mytools

# projects in header index
projects:
  - name: Machine-Learning-Notes
    url: https://github.com/skylinebin/Machine-Learning-Notes
  - name: PythonSpider
    url: https://github.com/skylinebin/PythonSpider
  - name: AlgorithmPractice
    url: https://github.com/skylinebin/AlgorithmPractice
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
